"""/seed_data/sample_msgs.py"""

sample_messages = [
    "Hey, how's it going?",
    "Did you check the update from yesterday?",
    "I'll be online in 5 minutes.",
    "Can you review my PR?",
    "Lunch was amazing today!",
    "Where did you find that meme?",
    "Let's sync up tomorrow morning.",
    "What’s the ETA on the report?",
    "I'm stuck on this bug again 😩",
    "Just deployed the latest version.",
    "Remember to backup the database.",
    "Anyone watching the match tonight?",
    "That’s a good point, actually.",
    "I'll send the document shortly.",
    "Wow, that was unexpected!",
    "Ping me when you're free.",
    "Who's up for a game later?",
    "Almost done with the task.",
    "Coffee break, anyone?",
    "You crushed it today!",
    "Happy Friday, folks!",
    "Where did we leave off?",
    "Can you share the link again?",
    "Totally agree with that.",
    "Let me explain it another way.",
    "I'm rebooting the server.",
    "Need help with this error log.",
    "Can someone cover for me tomorrow?",
    "Meeting pushed to 3pm.",
    "LOL that was hilarious!",
    "Don't forget to commit changes.",
    "We should brainstorm that.",
    "Heading out, see you tomorrow!",
    "You’re muted 😅",
    "Let's pair on this.",
    "Thanks for the quick fix!",
    "I'll handle the deployment.",
    "Great job on the demo!",
    "What’s our priority today?",
    "Anyone seen my headphones?",
    "Just testing something.",
    "The logs are weird today.",
    "Let’s keep it simple.",
    "You read my mind!",
    "Where are we hosting the files?",
    "No worries, I got it.",
    "Need a second opinion here.",
    "Just joined the call.",
    "Looks like a caching issue.",
    "We’re live 🚀",
    "What time is the retro?",
    "I’m learning a lot from this!",
    "Running a quick test now.",
    "Which branch should I use?",
    "I'll merge once CI passes.",
    "Push it to staging first.",
    "That feature is super useful.",
    "Mind reviewing my code?",
    "I’ll be right back.",
    "Just dropped a new commit.",
    "This part’s a bit tricky.",
    "Can we circle back to this?",
    "I’m still debugging this.",
    "You’re a lifesaver!",
    "Almost there!",
    "Which ticket is that?",
    "Slack is acting up again.",
    "That makes total sense now.",
    "Let’s deploy after lunch.",
    "Do we have test coverage for this?",
    "Yes, it’s reproducible.",
    "Mind if I take this one?",
    "I’ll write the documentation.",
    "Meeting was super productive.",
    "Need a break from the screen.",
    "Make sure to pull latest changes.",
    "That screenshot helped a lot!",
    "Should we log this as a bug?",
    "I added a comment on the issue.",
    "Where's the staging URL?",
    "I’ll clean up the commit history.",
    "Could use a second pair of eyes.",
    "Definitely needs more testing.",
    "I'll write a script for that.",
    "That's not expected behavior.",
    "Mind joining a quick huddle?",
    "Tried turning it off and on again?",
    "Looks good to me!",
    "Let’s write a test case for this.",
    "I'm all set for the demo.",
    "Trying a different approach now.",
    "Pushed a hotfix.",
    "Awesome progress today!",
    "Need to double-check this logic.",
    "Will follow up after the call.",
    "Let’s document that too.",
    "Happy to help!",
    "Review requested 👍",
    "Looping in @dev_team",
    "I’ll handle the rollback.",
    "Catch you all later!",
    "Almost forgot to push 😅",
    "Bug confirmed on my end too.",
    "That regex is terrifying 😅",
    "We can ship it 🚢",
]
